In [116]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [117]:
df=pd.read_csv('Student_Performance.csv')
df

,Hours Studied,Previous Scores,Extracurricular Activities,Sleep Hours,Sample Question Papers Practiced,Performance Index
0,7,99,Yes,9,1,91.0
1,4,82,No,4,2,65.0
2,8,51,Yes,7,2,45.0
3,5,52,Yes,5,2,36.0
4,7,75,No,8,5,66.0
...,...,...,...,...,...,...
9995,1,49,Yes,4,2,23.0
9996,7,64,Yes,8,5,58.0
9997,6,83,Yes,8,5,74.0
9998,9,97,Yes,7,0,95.0
9999,7,74,No,8,1,64.0

In [113]:
df.columns

Index(['Hours Studied', 'Previous Scores', 'Extracurricular Activities',
       'Sleep Hours', 'Sample Question Papers Practiced', 'Performance Index'],
      dtype='object')

In [68]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 6 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   Hours Studied                     10000 non-null  int64
 1   Previous Scores                   10000 non-null  int64
 2   Extracurricular Activities        10000 non-null  object
 3   Sleep Hours                       10000 non-null  int64
 4   Sample Question Papers Practiced  10000 non-null  int64
 5   Performance Index                 10000 non-null  float64
dtypes: float64(1), int64(4), object(1)
memory usage: 468.9+ KB

In [114]:
df.describe()

,Hours Studied,Previous Scores,Extracurricular Activities,Sleep Hours,Sample Question Papers Practiced,Performance Index
count,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000
mean,4.992900,69.445700,0.494800,6.530600,4.583300,55.224800
std,2.589309,17.343152,0.499998,1.695863,2.867348,19.212558
min,1.000000,40.000000,0.000000,4.000000,0.000000,10.000000
25%,3.000000,54.000000,0.000000,5.000000,2.000000,40.000000
50%,5.000000,69.000000,0.000000,7.000000,5.000000,55.000000
75%,7.000000,85.000000,1.000000,8.000000,7.000000,71.000000
max,9.000000,99.000000,1.000000,9.000000,9.000000,100.000000

In [69]:
df.isnull().sum()

Hours Studied                       0
Previous Scores                     0
Extracurricular Activities          0
Sleep Hours                         0
Sample Question Papers Practiced    0
Performance Index                   0
dtype: int64

In [118]:
df['Extracurricular Activities'].value_counts()

Extracurricular Activities
No     5052
Yes    4948
Name: count, dtype: int64

In [71]:
df.duplicated().value_counts()

False    9873
True      127
Name: count, dtype: int64

In [72]:
df.duplicated().sum()

np.int64(127)

In [73]:
duplicates=df.duplicated()
dup_records=df[duplicates]
dup_records

## we can use drop_duplicates()  to drop duplicates records
## df_no_duplicates= df.drop_duplicates()

,Hours Studied,Previous Scores,Extracurricular Activities,Sleep Hours,Sample Question Papers Practiced,Performance Index
915,9,52,No,5,9,48.0
1477,7,61,Yes,6,8,54.0
1601,5,99,No,7,5,89.0
1786,2,62,Yes,9,4,40.0
2026,5,87,Yes,6,7,74.0
...,...,...,...,...,...,...
9644,4,91,Yes,4,3,71.0
9940,8,95,No,5,2,90.0
9954,6,97,No,8,7,92.0
9966,1,41,No,7,3,12.0
9985,8,99,No,5,5,92.0

In [119]:
df

,Hours Studied,Previous Scores,Extracurricular Activities,Sleep Hours,Sample Question Papers Practiced,Performance Index
0,7,99,Yes,9,1,91.0
1,4,82,No,4,2,65.0
2,8,51,Yes,7,2,45.0
3,5,52,Yes,5,2,36.0
4,7,75,No,8,5,66.0
...,...,...,...,...,...,...
9995,1,49,Yes,4,2,23.0
9996,7,64,Yes,8,5,58.0
9997,6,83,Yes,8,5,74.0
9998,9,97,Yes,7,0,95.0
9999,7,74,No,8,1,64.0

In [120]:
from sklearn.preprocessing import LabelEncoder,StandardScaler
le=LabelEncoder()
df['Extracurricular Activities']=le.fit_transform(df['Extracurricular Activities'])
df.head()

,Hours Studied,Previous Scores,Extracurricular Activities,Sleep Hours,Sample Question Papers Practiced,Performance Index
0,7,99,1,9,1,91.0
1,4,82,0,4,2,65.0
2,8,51,1,7,2,45.0
3,5,52,1,5,2,36.0
4,7,75,0,8,5,66.0

In [121]:
x=df.drop('Performance Index',axis=1)
y=df['Performance Index']

In [122]:
print(x.shape,y.shape)

(10000, 5) (10000,)

In [123]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [124]:
scaler=StandardScaler()
x_train_scaled=scaler.fit_transform(x_train)
x_test_scaled=scaler.transform(x_test)

In [125]:
x_train_scaled

array([[ 0.00645547, -1.18384439, -0.98930717,  0.26988848,  0.13404112],
       [-1.14974745, -1.24150571,  1.01080841,  0.26988848,  0.48356164],
       [-1.14974745,  0.66131759, -0.98930717,  0.26988848, -0.91452044],
       ...,
       [ 1.54805935, -1.24150571, -0.98930717,  0.26988848,  0.48356164],
       [-1.53514842, -1.29916702, -0.98930717,  1.4474766 , -1.61356148],
       [-1.14974745, -1.35682833, -0.98930717, -0.31890558,  0.48356164]],
      shape=(8000, 5))

In [126]:
from sklearn.linear_model import LinearRegression
model=LinearRegression()
model.fit(x_train_scaled,y_train)

LinearRegression()

In [127]:
print(model.intercept_)
print(model.coef_)

55.31150000000001
[ 7.40134079 17.63727127  0.30429076  0.81003107  0.54884171]

In [128]:
y_pred=model.predict(x_test_scaled)
y_pred

array([54.71185392, 22.61551294, 47.90314471, ..., 16.79341955,
       63.34327368, 45.94262301], shape=(2000,))

In [129]:
from sklearn.metrics import r2_score,adjusted_rand_score
print('r2_score :',r2_score(y_test,y_pred))
print('adjusted_rand_score :',adjusted_rand_score(y_test,y_pred))

r2_score : 0.9889832909573145
adjusted_rand_score : 0.00025254542110780093

c:\Users\DELL\anaconda3\envs\lin_env\Lib\site-packages\sklearn\metrics\cluster\_supervised.py:59: UserWarning: Clustering metrics expects discrete values but received multiclass values for label, and continuous values for target
  warnings.warn(msg, UserWarning)

In [130]:
import pickle
import joblib

with open('student_final_model_1.pkl','wb') as file:
    pickle.dump((model,scaler,le),file)

In [102]:
with open('my_model_joblib.pkl','wb') as file:
    joblib.dump((model,scaler,le),file)

In [104]:
m,s,l=joblib.load('my_model_joblib.pkl','r+')

In [105]:
print(m)

LinearRegression()

In [107]:
print(s)

StandardScaler()